config/routes.rb
StudySpace::Application.routes.draw do
  resources :sound_levels, :only => [:new]
  resources :ratings, :only => [:new]
  resources :checkins, :only => [:new]
  resources :statuses, :only => [:new, :create, :update, :destroy]
  resources :users, :only => [:show, :create, :update, :destroy]
  resources :spots

  root 'welcome#index'

  

end

app/models/spot.rb
class Spot < ActiveRecord::Base
	has_many :statuses, dependent: :destroy
	has_many :checkins, dependent: :destroy
	has_many :ratings, dependent: :destroy
	has_many :sound_level, dependent: :destroy
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "Admin", password: ENV["ADMIN_PASS"], only: [:edit, :update, :create, :destroy]

  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    @status = Status.new
    @top_statuses = @spot.statuses.last(3)
    @missing_count = 3 - @top_statuses.count
    @w_type = resolve_type @spot.stype
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render action: 'show', status: :created, location: @spot }
      else
        format.html { render action: 'new' }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      params.require(:spot).permit(:name, :location, :description, :type, :current_sound_level, :rating, :rating_count, :checkin_count)
    end

    def restrict
      http_basic_authenticate_with :password => ENV['ADMIN_PASS']
    end

    def resolve_type id
      if id.to_i == 0
        return "Inside"
      elsif id.to_i == 1
        return "Outside"
      elsif id.to_i == 2
        return "Hybrid"
      else
        return "Special"
      end 
    end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stype %><br>
    <%= f.number_field :stype %>
  </div>
  <div class="field">
    <%= f.label :current_sound_level %><br>
    <%= f.text_field :current_sound_level %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </div>
  <div class="field">
    <%= f.label :rating_count %><br>
    <%= f.number_field :rating_count %>
  </div>
  <div class="field">
    <%= f.label :checkin_count %><br>
    <%= f.number_field :checkin_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<h1>Editing spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<div class="jumbotron text-center">
  <h1>Study Spots</h1>
  <p>Browse study spots around UC Davis</p>
</div>

<div class="list-group">
  <% Spot.all.each do |spt| %>
    <div class="list-group-item gr">
      <h4 class="list-group-item-heading"><%= spt.name %><span class="badge"><%= spt.checkin_count %></span></h4>
      <p class="list-group-item-text"><%= spt.description %></p>
      <div class="btn-group learn_more"><%= link_to "Learn more", spot_path(:id => spt.id), class: "btn btn-default" %></div>
    </div>
  <% end %>
  
</div>



<%= link_to 'Admin? - New Spot', new_spot_path %>

app/views/spots/new.html.erb
<h1>New spot</h1>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
<div class="container">
   <div class="page-header">
      <div class="row header_row">
         <div class="col-sm-4">
            <div class="text-left head-left"><img src="/assets/study_space_logo.png" style="width:102px; height:82px;"></div>
         </div>
         <div class="col-sm-4">
            <div class="text-center head-center">
               <h1 class="text-center"><%= @spot.name %></h1>
            </div>
         </div>
      </div>
   </div>
   <div class="custom_center">
      <span>
      <%= link_to '<i class="glyphicon glyphicon-map-marker map-marker" aria-hidden="true"></i>'.html_safe, new_checkin_path(spot_id: @spot.id.to_i)%>                
      </span><%= @spot.location %>   Click the icon to check in!
   </div>
   <div class="text-center special-font">
      <div class="row row-padding">
         <div class="col-sm-4">
            <div class="text-right">
            <% @spot.rating.ceil.to_i.times do %>
               <span class="glyphicon glyphicon-star star" aria-hidden="true"></span>
            <% end %>
            </div>
         </div>
         <div class="col-sm-4">
            <div class="text-center">
              <% if @spot.current_sound_level.ceil.to_i == 1 %>
               <span class="glyphicon glyphicon-volume-off vol-off" aria-hidden="true"></span>
              <% elsif @spot.current_sound_level.ceil.to_i == 2 %>
               <span class="glyphicon glyphicon-volume-down vol-down" aria-hidden="true"></span>
              <% else %>
                <span class="glyphicon glyphicon-volume-up vol-up" aria-hidden="true"></span>                 
               <% end %>
            </div>
         </div>
         <div class="col-sm-4">
            <div class="text-left"><%= @w_type %></div>
         </div>
      </div>
   </div>
   <img class="center-block" src="http://universityofcalifornia.edu/sites/default/files/mrak-hall-uc-davis.jpeg">
   <div class="description">
      <p><%= @spot.description %></p>
   </div>
   <hr />
   <div class="row">
      <% @top_statuses.each do |stat| %>
        <div class="col-sm-4">
           <p class="text-box2"><%= stat.description %><br/><small><%= User.find(stat.user_id).uname %></small></p>
        </div>
      <% end %>

      <% if @missing_count > 0 %>
        <% @missing_count.to_i.times do %>
          <div class="col-sm-3">
           <p class="text-box2">Holy cow! No Status???? </p>
        </div>
        <% end %>
      <% end %>
      
   </div>

   <div class="row row2-padding">
      <div class="col-sm-4">
         <div class="text-right">
            <label for="rating">Rating:</label>
            <% 5.times do |z| %>
              <%= link_to '<i class="glyphicon glyphicon-star-empty star2"></i>'.html_safe, new_rating_path(spot_id: @spot.id.to_i, value: (5 - z)) %>                
            <% end %>
         </div>
      </div>
      <div class="col-sm-4"></div>
      <div class="col-sm-4">
         <div class="text-left">
            <label for="sound_level">Sound Level:</label>
            <%= link_to '<i class="glyphicon glyphicon-volume-off vol"></i>'.html_safe, new_sound_level_path(spot_id: @spot.id.to_i, value: 1)%>                
            <%= link_to '<i class="glyphicon glyphicon-volume-down vol"></i>'.html_safe, new_sound_level_path(spot_id: @spot.id.to_i, value: 2)%>                
            <%= link_to '<i class="glyphicon glyphicon-volume-up vol"></i>'.html_safe, new_sound_level_path(spot_id: @spot.id.to_i, value: 3)%>                
         </div>
      </div>
      <div class="btn-group learn_more mdi"><%= link_to "Return", user_path(:id => cookies[:u_id]), class: "btn btn-default" %></div>

   </div>
   <%= render 'shared/status_update' %>

</div>