config/routes.rb
StudySpace::Application.routes.draw do
  resources :sound_levels, :only => [:new]
  resources :ratings, :only => [:new]
  resources :checkins, :only => [:new]
  resources :statuses, :only => [:new, :create, :update, :destroy]
  resources :users, :only => [:show, :create, :update, :destroy]
  resources :spots

  root 'welcome#index'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :statuses, dependent: :destroy
	has_many :checkins, dependent: :destroy
	has_many :ratings, dependent: :destroy
	has_many :sound_level, dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "Admin", password: ENV["ADMIN_PASS"], only: [:destroy, :update, :edit]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @local = @user.checkins.last(3)
    @global = Checkin.all.last(3)
  end

  # GET /users/new
  def new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.create(params[:uname])
    respond_to do |format|
      if @user.save
        cookies[:u_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { redirect_to :action , notice: 'User was successfully created.' }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(cookies[:u_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:uname, :ip_adr)
    end

    def restrict
      http_basic_authenticate_with :password => ENV['ADMIN_PASS']
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uname %><br>
    <%= f.text_area :uname %>
  </div>
  <div class="field">
    <%= f.label :ip_adr %><br>
    <%= f.text_area :ip_adr %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Uname</th>
      <th>Ip adr</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.uname %></td>
        <td><%= user.ip_adr %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container">
	<div class="page-header">
		<div class="text-center logo"><a href="study-space.herokuapp.com"><img style="width: 342px; height: 94px;" src="/assets/study_space_title_logo.png" alt="" /></a></div>
		<br/><br/>
		<div class="text-center welcome">
			<p id="welcome">Hello, <%= User.find(cookies[:u_id]).uname%>!</p>
		</div>
	</div>
	<div class="text-center into btn-group"><%= link_to "See all study spots near you!", spots_path(), class: "btn btn-default"%></div>
</div>
<p>&nbsp;</p>
<div class="well well-sm">
	<div class="row header">
		<div class="col-md-3">&nbsp;</div>
		<div class="col-md-3">
			<div class="text-center">
				<div class="visited">
					<h3>Your Visited Spaces</h3>
				</div>
			</div>
		</div>
		<div class="col-md-3 text-center other">
			<h3>Other Popular Spaces</h3>
		</div>
	</div>
</div>

<div class="row spaces_panel">
	<div class="col-md-3", id="left-col">
		<div class="text-center">
			<% @local.each do |check| %>
			<div class="panel panel-default">
				<div class="panel-heading panel1">
					<h3 class="panel-title"><%= Spot.find(check.spot_id.to_i).name %></h3>
				</div>
				<div class="panel-body body1"><%= Spot.find(check.spot_id.to_i).description %></div>
				<div class="btn-group learn_more"><%= link_to "Learn more", spot_path(:id => check.spot_id), class: "btn btn-default" %></div>
			</div>
			<% end %>

			
		</div>
	</div>

	<div class="col-md-3", id="right-col">
		<div class="text-center">
			<% @global.each do |check| %>
			<div class="panel panel-default">
				<div class="panel-heading panel1">
					<h3 class="panel-title"><%= Spot.find(check.spot_id.to_i).name %></h3>
				</div>
				<div class="panel-body body1"><%= Spot.find(check.spot_id.to_i).description %></div>
				<div class="btn-group learn_more"><%= link_to "Learn more", spot_path(:id => check.spot_id), class: "btn btn-default" %></div>
			</div>
			<% end %>

		</div>
	</div>

</div>